spring:
  profiles:
    active: ${PROFILE:dev}
  security:
    oauth:
      grantTypes: password,refresh_token
      refreshTokenValiditySeconds: '9600'
      accessTokenValiditySeconds: '9600'
      clientSecret: k4fk4
      clientId: kafka
      scopes: read,write
    user:
      password: p4ssw0rd
      name: admin
  data:
    rest:
      basePath: /api
logging:
  level:
    org:
      hibernate:
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
        SQL: DEBUG
server:
  error:
    include-binding-errors: always
    include-message: always
  port: ${PORT:8080}
