--INSERT INTO libro (isbn, autor, anioPublicacion, titulo, imagenUrl, idioma, formato)
--VALUES ('978-3-16-148410-0', 'Frank Kafka', 1915, 'La metamorfosis', '#', 'Ingles', 'Epub');
--
--INSERT INTO libro (isbn, autor, anioPublicacion, titulo, imagenUrl, idioma, formato)
--VALUES ('978-3-16-148410-1', 'Yuval Noah Harari', 2016, 'Homo Deus', '#', 'Ingles', 'Epub');
--
--INSERT INTO libro (isbn, autor, anioPublicacion, titulo, imagenUrl, idioma, formato)
--VALUES ('978-3-16-148410-2', 'Dante Alighieri', 1472, 'La divina comedia', '#', 'Ingles', 'Epub');
--
--INSERT INTO genero (genero, libros)
--VALUES ('novela',);
--
--INSERT INTO genero (genero, libros)
--VALUES ('ensayo',);
--
--INSERT INTO genero (genero, libros)
--VALUES ('poema',);
--
--INSERT INTO usuario (nombre, correo, edad, password, generos, ROLE, enabled)
--VALUES ('ADMINISTRATOR', 'KAFKA', 'ESCOM', '1996-01-30', 'MALE', 'admin@gmail.com', '$2y$12$zsnqNBPA32JmW5m6MocMT.R0Kl5wCAOKJR.0QGsnAvHFp1edLVu5K', '55 6677 8899', 'ADMINISTRATOR', 1);