drop table if exists genero CASCADE
drop table if exists libro CASCADE
drop table if exists libro_genero CASCADE
drop table if exists usuario CASCADE
drop table if exists usuario_genero CASCADE
drop table if exists usuario_libro CASCADE
create table genero (id_genero integer generated by default as identity, genero varchar(255), primary key (id_genero))
create table libro (id_libro integer generated by default as identity, anio_publicacion integer, autor varchar(255), formato varchar(255), idioma varchar(255), imagen_url varchar(255), isbn varchar(255), titulo varchar(255), primary key (id_libro))
create table libro_genero (id_libro integer not null, id_genero integer not null)
create table usuario (id_usuario integer generated by default as identity, correo varchar(255), edad integer, enabled BOOLEAN DEFAULT false not null, expired_account BOOLEAN DEFAULT false not null, expired_credentials BOOLEAN DEFAULT false not null, locked_account BOOLEAN DEFAULT false not null, nombre varchar(255), password varchar(255), role varchar(255) not null, primary key (id_usuario))
create table usuario_genero (id_usuario integer not null, id_genero integer not null)
create table usuario_libro (id_libro integer not null, id_usuario integer not null, puntuacion integer check (puntuacion>=1 AND puntuacion<=10), primary key (id_libro, id_usuario))
alter table libro add constraint UK_ehuya6b4bxgkc4ru5wcf5njgr unique (isbn)
alter table usuario add constraint UK_2mlfr087gb1ce55f2j87o74t unique (correo)
alter table usuario_libro add constraint UK_ghixc9ih5u5u89g5ox3itmi2i unique (id_libro)
alter table usuario_libro add constraint UK_ql4fv8nq7q1sc7hgqf7f93stq unique (id_usuario)
alter table libro_genero add constraint FKop2lw5gd7hkb62ae09orsogxc foreign key (id_genero) references genero
alter table libro_genero add constraint FK7l483fnkevg7q0cx5l3glx8c8 foreign key (id_libro) references libro
alter table usuario_genero add constraint FK6xbaehmlj7h3mx9n1gt2544x9 foreign key (id_genero) references genero
alter table usuario_genero add constraint FKp2q4ltqqf1vlaxqdreo1rc189 foreign key (id_usuario) references usuario
alter table usuario_libro add constraint FKinyw11wfg2hdvs5nc79rvvy5c foreign key (id_libro) references libro
alter table usuario_libro add constraint FKelgoc7l4wj22sw9j550wtsh8l foreign key (id_usuario) references usuario